// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type SupabaseRuntimeConfig = {
  VITE_SUPABASE_URL: string;
  VITE_SUPABASE_PUBLISHABLE_KEY: string;
};

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: Partial<SupabaseRuntimeConfig>;
  }
}

const runtimeConfig = window.__RUNTIME_CONFIG__;
if (!runtimeConfig?.VITE_SUPABASE_URL) throw new Error('Missing Supabase config: VITE_SUPABASE_URL');
if (!runtimeConfig?.VITE_SUPABASE_PUBLISHABLE_KEY) throw new Error('Missing Supabase config: VITE_SUPABASE_PUBLISHABLE_KEY');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(runtimeConfig.VITE_SUPABASE_URL, runtimeConfig.VITE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});